### ISSUE TITLE
Vera Can't Detect Device!

### ISSUE THREAD

**Issue by givanildo** [reneboer/vera-SolarMeter#1]
Sorry about my bad English!
I could not add the fronius in this plugin. I put Ip and number, but vera Can't Detect Device!
The only field with blank value is the  Syslog server IP Address:Port.
Please let me know about something .
And thank you!!! Nice Work !!! Amazing!!!

Posts: 4
Karma: +0/-0
View Profile  Personal Message (Online)

Re: Plugin: Solar Meter, universal Solar Production meter
« Reply #8 on: April 12, 2018, 05:08:57 pm »
QuoteModifyRemove
IP_FRONIUS/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData

   "Body" : {
      "Data" : {
         "DAY_ENERGY" : {
            "Unit" : "Wh",
            "Value" : 31221
         },
         "DeviceStatus" : {
            "ErrorCode" : 0,
            "LEDColor" : 2,
            "LEDState" : 0,
            "MgmtTimerRemainingTime" : -1,
            "StateToReset" : false,
            "StatusCode" : 7
         },
         "FAC" : {
            "Unit" : "Hz",
            "Value" : 60.009999999999998
         },
         "IAC" : {
            "Unit" : "A",
            "Value" : 0.56000000000000005
         },
         "IDC" : {
            "Unit" : "A",
            "Value" : 0.40000000000000002
         },
         "PAC" : {
            "Unit" : "W",
            "Value" : 129
         },
         "TOTAL_ENERGY" : {
            "Unit" : "Wh",
            "Value" : 318161
         },
         "UAC" : {
            "Unit" : "V",
            "Value" : 232.80000000000001
         },
         "UDC" : {
            "Unit" : "V",
            "Value" : 405.69999999999999
         },
         "YEAR_ENERGY" : {
            "Unit" : "Wh",
            "Value" : 318161.5
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DataCollection" : "CommonInverterData",
         "DeviceClass" : "Inverter",
         "DeviceId" : "1",
         "Scope" : "Device"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2018-04-12T16:59:02-04:00"
   }
}

**Comment by givanildo** [comment]
I don't know , but in file L_SolarMeter1.lua . may be wrong

-- Put known systems routines in map, keep in sync with J_SolarMeter.js var solarSystem
	addSolarSystem(1, SS_EnphaseLocal_Init, SS_EnphaseLocal_Refresh)
	addSolarSystem(2, SS_EnphaseRemote_Init, SS_EnphaseRemote_Refresh)
	addSolarSystem(3, SS_SolarEdge_Init, SS_SolarEdge_Refresh)
	addSolarSystem(4, SS_PVOutput_Init, SS_PVOutput_Refresh)
	addSolarSystem(5, SS_SunGrow_Init, SS_SunGrow_Refresh)
	********addSolarSystem(6, SS_FroniusAPI_Init, SS_FroniusAPI_Refresh)************

**Comment by givanildo** [comment]
And this line ...
watts = tonumber(retData.PAC.Value)

I didn’t see “PAC” in return URL

**Comment by givanildo** [comment]
Sorry.  PAC is there

**Comment by reneboer** [comment]
Hi @givanildo 
Please install the V1.3 L_SolarMeter1.lua file and let me know if it is fixed.

**Comment by givanildo** [comment]
Att.: Givanildo Brunetta
            6699552704


Em 16 de abr de 2018, à(s) 15:04, reneboer <notifications@github.com> escreveu:

**Comment by givanildo** [comment]
This week   and This month   Is value 0

Last update 23:01 31 Dec ???







Att.: Givanildo Brunetta
            6699552704

**Comment by givanildo** [comment]
Ok. I understood. One question...
May you could put the voltage and current values in the plugin.   
It is IAC IDC and UAC 
I don t know if this is relevant 

Att.: Givanildo Brunetta
            6699552704


Em 16 de abr de 2018, à(s) 16:19, reneboer <notifications@github.com> escreveu:

**Comment by reneboer** [comment]
The ICD, IAC, UAC and UDC fields will be put in a variable with V1.4.1 posted here. Note that you will not see them on the Vera UI as that is not very flexible.

**Comment by givanildo** [comment]
Thank you.  

Att.: Givanildo Brunetta
            6699552704


Em 18 de abr de 2018, à(s) 09:32, reneboer <notifications@github.com> escreveu:
