### ISSUE TITLE
SolarEdge is not updating

### ISSUE THREAD

**Issue by RolfKoolma** [reneboer/vera-SolarMeter#6]
I use SolarMeter with my SolarEdge system.
It seems that there is something wrong with updating the values from SolarEdge. When I restart the SolarMeter plugin I get new values, so the interface (API calls with API key) does work.
I have tried with different poll interval settings.

**Comment by RolfKoolma** [comment]
Did some extra debugging.
In the LuaUPnP.log I see:
ing1 variable: KWHReading was: 1579095660 now: 1579095810 #hooks: 0 upnp: 0 skip: 0 v:(nil)/NONE duplicate:0 <0x76ee4520>
06      01/15/20 14:44:06.181   Device_Variable::m_szValue_set device: 71 service: urn:micasaverde-com:serviceId:EnergyMetering1 variable: KWHReading was: 1579095810 now: 1579095846 #hooks: 0 upnp: 0 skip: 0 v:(nil)/NONE duplicate:0 <0x76ee4520>
06      01/15/20 14:44:31.103   Device_Variable::m_szValue_set device: 107 service: urn:micasaverde-com:serviceId:EnergyMetering1 variable: KWHReading was: 1579095739 now: 1579095871 #hooks: 0 upnp: 0 skip: 0 v:(nil)/NONE duplicate:0 <0x76ee4520>
06      01/15/20 14:45:00.371   Device_Variable::m_szValue_set device: 41 service: urn:micasaverde-com:serviceId:EnergyMetering1 variable: KWHReading was: 1579095750 now: 1579095900 #hooks: 0 upnp: 0 skip: 0 v:(nil)/NONE duplicate:0 <0x76ee4520>
06      01/15/20 14:45:30.411   Device_Variable::m_szValue_set device: 28 service: urn:micasaverde-com:serviceId:EnergyMetering1 variable: KWHReading was: 1579095780 now: 1579095930 #hooks: 0 upnp: 0 skip: 0 v:(nil)/NONE duplicate:0 <0x76ee4520>
06      01/15/20 14:46:00.741   Device_Variable::m_szValue_set device: 71 service: urn:micasaverde-com:serviceId:EnergyMeter

While using a curl command to get the data from the monitoring API I get:
curl https://monitoringapi.solaredge.com/site/<site id>/overview.json?api_key=<my_api_key>
{"overview":{"lastUpdateTime":"2020-01-15 14:45:38","lifeTimeData":{"energy":6789032.0},"lastYearData":{"energy":36195.0},"lastMonthData":{"energy":36195.0},"lastDayData":{"energy":3161.0},"currentPower":{"power":72.66653},"measuredBy":"INVERTER"}}

**Comment by reneboer** [comment]
Hi Rolf,
I can see what goes wrong. I will have to do some number conversion on the value returned. It does not seem to like the Solar Edge API returns a fractional number.

**Comment by reneboer** [comment]
Fixed with version 1.14.
